NRICH:
    acknowledgement: Reproduced by kind permission of NRICH.
CamAss:
    acknowledgement: Reproduced by permission of Cambridge Assessment Group Archives
UKMT:
    acknowledgement: Reproduced by kind permission of the United Kingdom Mathematics Trust
